#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/usr/bin/at-server-c
PROG_NAME="at-server-c"

. /lib/functions.sh

setup_firewall() {
	local allow_wan ws_port module_allow_wan restrict_module module_host module_port

	config_load at-webserver
	config_get_bool allow_wan config websocket_allow_wan 0
	config_get ws_port config websocket_port 8765
	config_get_bool module_allow_wan config network_allow_wan 0
	config_get_bool restrict_module config network_restrict_access 0
	config_get module_host config network_host '192.168.8.1'
	config_get module_port config network_port '20249'

	local rules="
at_webserver_wan_block
at_webserver_wan_allow
at_module_restrict
at_module_wan_block
at_module_wan_allow
"

	for rule_name in $rules; do
		local rule_idx="$(uci show firewall | grep "\.name='$rule_name'" | cut -d'[' -f2 | cut -d']' -f1 | head -n1)"
		[ -n "$rule_idx" ] && uci delete firewall.@rule[$rule_idx] 2>/dev/null
	done

	if [ "$module_allow_wan" -eq 1 ]; then
		uci add firewall rule >/dev/null
		uci set firewall.@rule[-1].name="at_module_wan_allow"
		uci set firewall.@rule[-1].src='wan'
		uci set firewall.@rule[-1].dest='*'
		uci set firewall.@rule[-1].dest_ip="$module_host"
		uci set firewall.@rule[-1].dest_port="$module_port"
		uci set firewall.@rule[-1].proto='tcp'
		uci set firewall.@rule[-1].target='ACCEPT'
		uci set firewall.@rule[-1].enabled='1'
	else
		uci add firewall rule >/dev/null
		uci set firewall.@rule[-1].name="at_module_wan_block"
		uci set firewall.@rule[-1].src='wan'
		uci set firewall.@rule[-1].dest='*'
		uci set firewall.@rule[-1].dest_ip="$module_host"
		uci set firewall.@rule[-1].dest_port="$module_port"
		uci set firewall.@rule[-1].proto='tcp'
		uci set firewall.@rule[-1].target='REJECT'
		uci set firewall.@rule[-1].enabled='1'
	fi

	if [ "$allow_wan" -eq 1 ]; then
		uci add firewall rule >/dev/null
		uci set firewall.@rule[-1].name="at_webserver_wan_allow"
		uci set firewall.@rule[-1].src='wan'
		uci set firewall.@rule[-1].proto='tcp'
		uci set firewall.@rule[-1].dest_port="$ws_port"
		uci set firewall.@rule[-1].target='ACCEPT'
		uci set firewall.@rule[-1].enabled='1'
	else
		uci add firewall rule >/dev/null
		uci set firewall.@rule[-1].name="at_webserver_wan_block"
		uci set firewall.@rule[-1].src='wan'
		uci set firewall.@rule[-1].proto='tcp'
		uci set firewall.@rule[-1].dest_port="$ws_port"
		uci set firewall.@rule[-1].target='REJECT'
		uci set firewall.@rule[-1].enabled='1'
	fi

	if [ "$restrict_module" -eq 1 ]; then
		uci add firewall rule >/dev/null
		uci set firewall.@rule[-1].name="at_module_restrict"
		uci set firewall.@rule[-1].src='lan'
		uci set firewall.@rule[-1].dest='*'
		uci set firewall.@rule[-1].dest_ip="$module_host"
		uci set firewall.@rule[-1].dest_port="$module_port"
		uci set firewall.@rule[-1].proto='tcp'
		uci set firewall.@rule[-1].target='REJECT'
		uci set firewall.@rule[-1].enabled='1'
	fi

	uci commit firewall
	/etc/init.d/firewall reload >/dev/null 2>&1
}

start_service() {
	local enabled

	config_load at-webserver
	config_get_bool enabled config enabled 0

	[ "$enabled" -eq 0 ] && {
		logger -t at-webserver "service disabled"
		return 1
	}

	[ ! -x "$PROG" ] && {
		logger -t at-webserver "binary not found: $PROG"
		return 1
	}

	setup_firewall
	killall -q -9 "$PROG_NAME" 2>/dev/null
	sleep 1

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param pidfile /var/run/at-webserver.pid
	procd_close_instance
}

stop_service() {
	killall -q -9 "$PROG_NAME" 2>/dev/null
	rm -f /var/run/at-webserver.pid
}

reload_service() {
	stop_service
	sleep 1
	start_service
}

service_triggers() {
	procd_add_reload_trigger "at-webserver"
}
